// AUTO-GENERATED by scripts/gen-ingredient-images.mjs — do not edit by hand.
// slug → aliases (lowercased) parsed from the source icon filenames.
// Images live at /public/ingredients/<slug>.png (128px, transparent).

export const INGREDIENT_IMAGE_ALIASES: Record<string, string[]> = {
  "agave-syrup": [
    "agave syrup"
  ],
  "alaska-seelachs": [
    "alaska-seelachs"
  ],
  "almond": [
    "almond"
  ],
  "almond-milk": [
    "almond milk"
  ],
  "amla-or-indian-gooseberry": [
    "amla or indian gooseberry",
    "amla",
    "indian gooseberry"
  ],
  "apfelschorlen": [
    "apfelschorlen"
  ],
  "apricot": [
    "apricot"
  ],
  "asafoetida-powder": [
    "asafoetida powder"
  ],
  "ash-gourd-or-winter-melon": [
    "ash gourd or winter melon",
    "ash gourd",
    "winter melon"
  ],
  "ashwagandha-powder": [
    "ashwagandha powder"
  ],
  "aubergine": [
    "aubergine"
  ],
  "avocado": [
    "avocado"
  ],
  "baby-shark-or-paal-sura": [
    "baby shark or paal sura",
    "baby shark",
    "paal sura"
  ],
  "bacon": [
    "bacon"
  ],
  "baguette": [
    "baguette"
  ],
  "baking-powder": [
    "baking powder"
  ],
  "baking-soda-natron": [
    "baking soda : natron",
    "baking soda",
    "natron"
  ],
  "balsamico": [
    "balsamico"
  ],
  "baltic-herring-fish": [
    "baltic herring fish"
  ],
  "banana": [
    "banana"
  ],
  "banana-leaf": [
    "banana leaf"
  ],
  "basil-leaves": [
    "basil leaves"
  ],
  "basil-seeds-or-sabja-seeds": [
    "basil seeds or sabja seeds",
    "basil seeds",
    "sabja seeds"
  ],
  "basmati-rice": [
    "basmati rice"
  ],
  "bay-leaf": [
    "bay leaf"
  ],
  "beet-root": [
    "beet root"
  ],
  "beluga-linsen": [
    "beluga linsen"
  ],
  "bergkase-mild": [
    "bergkäse mild"
  ],
  "besan-or-gram-flour": [
    "besan or gram flour",
    "besan",
    "gram flour"
  ],
  "bitter-gourd": [
    "bitter gourd"
  ],
  "black-beans": [
    "black beans"
  ],
  "black-eyed-beans-or-peas": [
    "black eyed beans or peas",
    "black eyed beans",
    "peas"
  ],
  "black-pepper": [
    "black pepper"
  ],
  "black-pepper-powder": [
    "black pepper powder"
  ],
  "black-raisins": [
    "black raisins"
  ],
  "black-sesame-seeds": [
    "black sesame seeds"
  ],
  "black-stone-flower-or-kalpasi": [
    "black stone flower or kalpasi",
    "black stone flower",
    "kalpasi"
  ],
  "black-truffle-mushroom": [
    "black truffle mushroom"
  ],
  "black-urad-dal": [
    "black urad dal"
  ],
  "blueberry": [
    "blueberry"
  ],
  "bottle-gourd": [
    "bottle gourd"
  ],
  "bourbon-vanille-extrakt": [
    "bourbon vanille extrakt"
  ],
  "bourbon-vanillezucker": [
    "bourbon vanillezucker"
  ],
  "bratol": [
    "bratöl"
  ],
  "brazil-nuts": [
    "brazil nuts"
  ],
  "breadcrumbs": [
    "breadcrumbs"
  ],
  "brinjal-indian": [
    "brinjal indian"
  ],
  "brioche-bread-loaf": [
    "brioche bread loaf"
  ],
  "briyani-masala-powder": [
    "briyani masala powder"
  ],
  "broad-beans": [
    "broad beans"
  ],
  "broccoli": [
    "broccoli"
  ],
  "brombeeren": [
    "brombeeren"
  ],
  "brotchen": [
    "brotchen"
  ],
  "brown-and-black-mustard-seeds": [
    "brown and black mustard seeds"
  ],
  "brown-chickpea-or-kala-channa": [
    "brown chickpea or kala channa",
    "brown chickpea",
    "kala channa"
  ],
  "brown-lentils": [
    "brown lentils"
  ],
  "brown-rice": [
    "brown rice"
  ],
  "brown-sugar": [
    "brown sugar"
  ],
  "bulgur": [
    "bulgur"
  ],
  "buschbohnen": [
    "buschbohnen"
  ],
  "butter": [
    "butter"
  ],
  "cabbage": [
    "cabbage"
  ],
  "canned-bambussprossen": [
    "canned bambussprossen"
  ],
  "canned-chickpea": [
    "canned chickpea"
  ],
  "canned-coconut-milk": [
    "canned coconut milk"
  ],
  "canned-erbsen": [
    "canned erbsen"
  ],
  "canned-kidney-beans": [
    "canned kidney beans"
  ],
  "canned-maiskolbchen": [
    "canned maiskölbchen"
  ],
  "canned-mungobohnenkeimlinge": [
    "canned mungobohnenkeimlinge"
  ],
  "canned-rote-bete": [
    "canned rote bete"
  ],
  "canned-rotkohl": [
    "canned rotkohl"
  ],
  "canned-sauerkraut": [
    "canned sauerkraut"
  ],
  "canned-sweet-corn": [
    "canned sweet corn"
  ],
  "canned-tomatoes": [
    "canned tomatoes"
  ],
  "canned-tuna-fish": [
    "canned tuna fish"
  ],
  "canned-white-beans": [
    "canned white beans"
  ],
  "capers": [
    "capers"
  ],
  "cardamom": [
    "cardamom"
  ],
  "cardamom-powder": [
    "cardamom powder"
  ],
  "carom-seeds": [
    "carom seeds"
  ],
  "carrot": [
    "carrot"
  ],
  "cashew-nut": [
    "cashew nut"
  ],
  "cauliflower": [
    "cauliflower"
  ],
  "cayennepfeffer-gemahlen": [
    "cayennepfeffer gemahlen"
  ],
  "celery": [
    "celery"
  ],
  "chaat-masala": [
    "chaat masala"
  ],
  "champignons-braun": [
    "champignons braun"
  ],
  "champignons-weiss": [
    "champignons weiss"
  ],
  "channa-dal": [
    "channa dal"
  ],
  "cheddar-cheese": [
    "cheddar cheese"
  ],
  "cherry": [
    "cherry"
  ],
  "cherry-tomato": [
    "cherry tomato"
  ],
  "chia-seeds": [
    "chia seeds"
  ],
  "chicken": [
    "chicken"
  ],
  "chicken-breast-fillet": [
    "chicken breast fillet"
  ],
  "chicken-masala": [
    "chicken masala"
  ],
  "chicken-stock-powder": [
    "chicken stock powder"
  ],
  "chilli-flakes": [
    "chilli flakes"
  ],
  "chilli-jalapeno": [
    "chilli jalapeno"
  ],
  "chilli-powder": [
    "chilli powder"
  ],
  "chinakohl": [
    "chinakohl"
  ],
  "chives": [
    "chives"
  ],
  "chocolate-spread": [
    "chocolate spread"
  ],
  "chow-chow": [
    "chow chow"
  ],
  "cinnamon-powder": [
    "cinnamon powder"
  ],
  "cinnamon-stick": [
    "cinnamon stick"
  ],
  "clove": [
    "clove"
  ],
  "cluster-beans": [
    "cluster beans"
  ],
  "coconut": [
    "coconut"
  ],
  "coconut-oil": [
    "coconut oil"
  ],
  "cod-fish-fillet": [
    "cod fish fillet"
  ],
  "coffee-bean": [
    "coffee bean"
  ],
  "cola": [
    "cola"
  ],
  "condensed-milk": [
    "condensed milk"
  ],
  "coriander-leaves": [
    "coriander leaves"
  ],
  "coriander-seeds": [
    "coriander seeds"
  ],
  "corinder-powder": [
    "corinder powder"
  ],
  "corn-flakes": [
    "corn flakes"
  ],
  "cornstarch": [
    "cornstarch"
  ],
  "couscous": [
    "couscous"
  ],
  "crab": [
    "crab"
  ],
  "cranberries": [
    "cranberries"
  ],
  "cream-of-tartar": [
    "cream of tartar"
  ],
  "creatine-monohydrate": [
    "creatine monohydrate"
  ],
  "croissant": [
    "croissant"
  ],
  "cucumber": [
    "cucumber"
  ],
  "cumin-powder": [
    "cumin powder"
  ],
  "cumin-seeds": [
    "cumin seeds"
  ],
  "curry-leaves": [
    "curry leaves"
  ],
  "curry-powder": [
    "curry powder"
  ],
  "custard-apple": [
    "custard apple"
  ],
  "dark-chocolate-bar": [
    "dark chocolate bar"
  ],
  "dark-chocolate-chips": [
    "dark chocolate chips"
  ],
  "dates": [
    "dates"
  ],
  "dijon-mustard": [
    "dijon mustard"
  ],
  "dill": [
    "dill"
  ],
  "dinkel-vollkornmehl": [
    "dinkel-vollkornmehl"
  ],
  "dinkelmehl-type-1050": [
    "dinkelmehl type 1050"
  ],
  "dinkelmehl-type-630": [
    "dinkelmehl type 630"
  ],
  "doenjang": [
    "doenjang"
  ],
  "doubanjiang": [
    "doubanjiang"
  ],
  "dragon-fruit": [
    "dragon fruit"
  ],
  "dried-anchovies": [
    "dried anchovies"
  ],
  "dried-chickpea": [
    "dried chickpea"
  ],
  "dried-corn-kernels": [
    "dried corn kernels"
  ],
  "dried-fig": [
    "dried fig"
  ],
  "dried-green-peas": [
    "dried green peas"
  ],
  "dried-oregano-leaves": [
    "dried oregano leaves"
  ],
  "dried-red-chillies": [
    "dried red chillies"
  ],
  "dried-tomatoes": [
    "dried tomatoes"
  ],
  "drumstick": [
    "drumstick"
  ],
  "dry-fenugreek-leaves": [
    "dry fenugreek leaves"
  ],
  "dry-ginger-powder-or-sokku": [
    "dry ginger powder or sokku",
    "dry ginger powder",
    "sokku"
  ],
  "dry-mango-powder": [
    "dry mango powder"
  ],
  "dry-tamarind": [
    "dry tamarind"
  ],
  "dry-yeast": [
    "dry yeast"
  ],
  "eadmame-bean": [
    "eadmame bean"
  ],
  "egg": [
    "egg"
  ],
  "egg-whites": [
    "egg whites"
  ],
  "egg-yolk": [
    "egg yolk"
  ],
  "eisbergsalat": [
    "eisbergsalat"
  ],
  "eistee": [
    "eistee"
  ],
  "electrolyte-tablets": [
    "electrolyte tablets"
  ],
  "elephant-foot-yam-or-suran": [
    "elephant foot yam or suran",
    "elephant foot yam",
    "suran"
  ],
  "emmentaler-hartkase": [
    "emmentaler hartkäse"
  ],
  "energy-drink": [
    "energy drink"
  ],
  "erdnussol": [
    "erdnussöl"
  ],
  "erythrit": [
    "erythrit"
  ],
  "espresso": [
    "espresso"
  ],
  "essigessenz": [
    "essigessenz"
  ],
  "farfalle": [
    "farfalle"
  ],
  "fenchel": [
    "fenchel"
  ],
  "fennel-seeds": [
    "fennel seeds"
  ],
  "fenugreek-leaves": [
    "fenugreek leaves"
  ],
  "fenugreek-powder": [
    "fenugreek powder"
  ],
  "fenugreek-seeds": [
    "fenugreek seeds"
  ],
  "feta": [
    "feta"
  ],
  "fettuccine": [
    "fettuccine"
  ],
  "fischsauce": [
    "fischsauce"
  ],
  "flattened-rice": [
    "flattened rice"
  ],
  "fleisch-tomaten": [
    "fleisch tomaten"
  ],
  "forelle-or-trout": [
    "forelle or trout",
    "forelle",
    "trout"
  ],
  "foxtail-millet": [
    "foxtail millet"
  ],
  "fresh-freen-pea": [
    "fresh freen pea"
  ],
  "frischkase-mit-gurke": [
    "frischkäse mit gurke"
  ],
  "frischkase-mit-paprika": [
    "frischkäse mit paprika"
  ],
  "fruit-jam": [
    "fruit jam"
  ],
  "fruit-tea": [
    "fruit tea"
  ],
  "fusilli": [
    "fusilli"
  ],
  "garam-masala": [
    "garam masala"
  ],
  "garlic": [
    "garlic"
  ],
  "garlic-powder": [
    "garlic powder"
  ],
  "gelatine-powder": [
    "gelatine powder"
  ],
  "gerebelt-basilikum": [
    "gerebelt basilikum"
  ],
  "gerebelt-majoran": [
    "gerebelt majoran"
  ],
  "gerebelt-thymian": [
    "gerebelt thymian"
  ],
  "geschnitten-rosmarin": [
    "geschnitten rosmarin"
  ],
  "ghee": [
    "ghee"
  ],
  "ginger": [
    "ginger"
  ],
  "ginger-garlic-paste": [
    "ginger-garlic paste"
  ],
  "ginger-tea": [
    "ginger tea"
  ],
  "glocon-d-glucose-powder": [
    "glocon-d glucose powder"
  ],
  "gnocchi": [
    "gnocchi"
  ],
  "gochugaru": [
    "gochugaru"
  ],
  "gochujang": [
    "gochujang"
  ],
  "gongura-or-pulicha-keerai": [
    "gongura or pulicha keerai",
    "gongura",
    "pulicha keerai"
  ],
  "gouda-jung": [
    "gouda jung"
  ],
  "grana-padano": [
    "grana padano"
  ],
  "grapefruit": [
    "grapefruit"
  ],
  "grapes": [
    "grapes"
  ],
  "greek-joghurt-10": [
    "greek joghurt 10%"
  ],
  "green-apple": [
    "green apple"
  ],
  "green-capsicum": [
    "green capsicum"
  ],
  "green-chilli": [
    "green chilli"
  ],
  "green-lentils": [
    "green lentils"
  ],
  "green-moong-bean": [
    "green moong bean"
  ],
  "green-peas": [
    "green peas"
  ],
  "green-tomato": [
    "green tomato"
  ],
  "grill-und-pfannenkase-krauter": [
    "grill und pfannenkäse kräuter"
  ],
  "guava": [
    "guava"
  ],
  "hackfleisch": [
    "hackfleisch"
  ],
  "halloumi": [
    "halloumi"
  ],
  "hazelnut": [
    "hazelnut"
  ],
  "himalayan-pink-rock-salt": [
    "himalayan pink rock salt"
  ],
  "hirtenkase": [
    "hirtenkäse"
  ],
  "hoisin-sauce": [
    "hoisin sauce"
  ],
  "holy-basil": [
    "holy basil"
  ],
  "homemade-powder": [
    "homemade powder"
  ],
  "honey": [
    "honey"
  ],
  "honey-dew-melon": [
    "honey dew melon"
  ],
  "horse-gram": [
    "horse gram"
  ],
  "hummus": [
    "hummus"
  ],
  "ice-cube": [
    "ice cube"
  ],
  "idli-rice": [
    "idli rice"
  ],
  "indo-pacific-king-mackeral-fish-cut": [
    "indo-pacific king mackeral fish cut"
  ],
  "instant-coffee-powder": [
    "instant coffee powder"
  ],
  "instant-noodles-or-ramen-block": [
    "instant noodles or ramen block",
    "instant noodles",
    "ramen block"
  ],
  "italienische-krauter": [
    "italienische kräuter"
  ],
  "ivy-gourd": [
    "ivy gourd"
  ],
  "jackfruit": [
    "jackfruit"
  ],
  "jaggery": [
    "jaggery"
  ],
  "jalapeno": [
    "jalapeño"
  ],
  "jasmin-reis": [
    "jasmin-reis"
  ],
  "joghurt": [
    "joghurt"
  ],
  "jowar-or-sorghum": [
    "jowar or sorghum",
    "jowar",
    "sorghum"
  ],
  "kaffir-lime-leaves": [
    "kaffir lime leaves"
  ],
  "kakao-zum-backen": [
    "kakao zum backen"
  ],
  "kashmiri-chilli-powder": [
    "kashmiri chilli powder"
  ],
  "kashmiri-red-chilli": [
    "kashmiri red chilli"
  ],
  "keimol": [
    "keimöl"
  ],
  "kevra-water": [
    "kevra water"
  ],
  "kidney-beans": [
    "kidney beans"
  ],
  "kimchi": [
    "kimchi"
  ],
  "kitchen-king-masala": [
    "kitchen king masala"
  ],
  "kiwi": [
    "kiwi"
  ],
  "kohlrabi": [
    "kohlrabi"
  ],
  "kurkuma": [
    "kurkuma"
  ],
  "lady-finger-or-okra": [
    "lady finger or okra",
    "lady finger",
    "okra"
  ],
  "ladysfinger-biscuit": [
    "ladysfinger biscuit"
  ],
  "lamb-meat": [
    "lamb meat"
  ],
  "lasagne": [
    "lasagne"
  ],
  "le-gruyere-hartkase": [
    "le gruyère hartkäse"
  ],
  "leinol": [
    "leinöl"
  ],
  "leinsaat": [
    "leinsaat"
  ],
  "lemon": [
    "lemon"
  ],
  "lemon-juice": [
    "lemon juice"
  ],
  "lemon-zest": [
    "lemon zest"
  ],
  "lemongrass": [
    "lemongrass"
  ],
  "lgm-crispy-chilli-in-oil": [
    "lgm-crispy-chilli-in-oil"
  ],
  "lima-beans": [
    "lima beans"
  ],
  "lime": [
    "lime"
  ],
  "lobster": [
    "lobster"
  ],
  "lotus-stem": [
    "lotus stem"
  ],
  "lychee": [
    "lychee"
  ],
  "macadamia-nuts": [
    "macadamia nuts"
  ],
  "mace-indian-spice": [
    "mace indian spice"
  ],
  "mango": [
    "mango"
  ],
  "maple-syrup": [
    "maple syrup"
  ],
  "masa-harina": [
    "masa harina"
  ],
  "mascarpone": [
    "mascarpone"
  ],
  "matcha-tea-powder": [
    "matcha tea powder"
  ],
  "mayonnaise": [
    "mayonnaise"
  ],
  "meat-masala": [
    "meat masala"
  ],
  "milchreis": [
    "milchreis"
  ],
  "milk": [
    "milk"
  ],
  "milk-chocolate": [
    "milk chocolate"
  ],
  "milk-chocolate-chips": [
    "milk chocolate chips"
  ],
  "mint-leaves": [
    "mint leaves"
  ],
  "mirin": [
    "mirin"
  ],
  "miso-paste": [
    "miso paste"
  ],
  "monosodium-glutamate-or-ajinomoto": [
    "monosodium glutamate or ajinomoto",
    "monosodium glutamate",
    "ajinomoto"
  ],
  "moong-dal": [
    "moong dal"
  ],
  "moringa-leaves": [
    "moringa leaves"
  ],
  "mozzarella": [
    "mozzarella"
  ],
  "multivitamin-supplement": [
    "multivitamin supplement"
  ],
  "muskmelon": [
    "muskmelon"
  ],
  "musli": [
    "müsli"
  ],
  "mussels": [
    "mussels"
  ],
  "mustard-oil": [
    "mustard oil"
  ],
  "nachos": [
    "nachos"
  ],
  "nori-sheets-seaweed": [
    "nori sheets seaweed"
  ],
  "north-sea-shrimp": [
    "north sea shrimp"
  ],
  "nutmeg": [
    "nutmeg"
  ],
  "oat-milk": [
    "oat milk"
  ],
  "oats": [
    "oats"
  ],
  "octopus": [
    "octopus"
  ],
  "olio-extra-vergine-di-oliva-kreta": [
    "olio extra vergine di oliva kreta"
  ],
  "olio-extra-vergine-di-oliva-spanien": [
    "olio extra vergine di oliva spanien"
  ],
  "omega-fish-oil-capsule": [
    "omega fish oil capsule"
  ],
  "onion": [
    "onion"
  ],
  "orange": [
    "orange"
  ],
  "orange-juice": [
    "orange juice"
  ],
  "ovomaltine": [
    "ovomaltine"
  ],
  "oyster": [
    "oyster"
  ],
  "oyster-sauce": [
    "oyster sauce"
  ],
  "pak-choi": [
    "pak choi"
  ],
  "panco-breadcrumbs": [
    "panco breadcrumbs"
  ],
  "paneer-cubes": [
    "paneer cubes"
  ],
  "papaya": [
    "papaya"
  ],
  "paprika-gelb": [
    "paprika gelb"
  ],
  "paprika-powder": [
    "paprika powder"
  ],
  "paprika-rot": [
    "paprika rot"
  ],
  "paratha": [
    "paratha"
  ],
  "parmigiano-reggiano": [
    "parmigiano reggiano"
  ],
  "parotta-malabar": [
    "parotta"
  ],
  "parsley": [
    "parsley"
  ],
  "passion-fruit": [
    "passion fruit"
  ],
  "pasta": [
    "pasta"
  ],
  "peach": [
    "peach"
  ],
  "peanut-butter": [
    "peanut butter"
  ],
  "peanut-or-groundnut": [
    "peanut or groundnut",
    "peanut",
    "groundnut"
  ],
  "pear": [
    "pear"
  ],
  "pearl-millet-or-bajra": [
    "pearl millet or bajra",
    "pearl millet",
    "bajra"
  ],
  "pearl-spot-or-karimeen": [
    "pearl spot or karimeen",
    "pearl spot",
    "karimeen"
  ],
  "pecorino-romano": [
    "pecorino romano"
  ],
  "penne": [
    "penne"
  ],
  "petersilie-glatt": [
    "petersilie glatt"
  ],
  "physalis": [
    "physalis"
  ],
  "pickeled-cucumber": [
    "pickeled cucumber"
  ],
  "pickled-green-olives": [
    "pickled green olives"
  ],
  "pickled-jalapeno": [
    "pickled jalapeño"
  ],
  "pickled-spanish-olives": [
    "pickled spanish olives"
  ],
  "pine-nut": [
    "pine nut"
  ],
  "pineapple": [
    "pineapple"
  ],
  "pineapple-flavouring-essence": [
    "pineapple flavouring essence"
  ],
  "pink-himalayan-salt-powder": [
    "pink himalayan salt powder"
  ],
  "pistachio": [
    "pistachio"
  ],
  "plainten-stem-or-vazhai-thandu": [
    "plainten stem or vazhai thandu",
    "plainten stem",
    "vazhai thandu"
  ],
  "plum": [
    "plum"
  ],
  "pomfret-fish": [
    "pomfret fish"
  ],
  "pomogranate": [
    "pomogranate"
  ],
  "ponni-boiled-rice": [
    "ponni boiled rice"
  ],
  "ponni-raw-rice": [
    "ponni raw rice"
  ],
  "poppy-seeds": [
    "poppy seeds"
  ],
  "pork-meat": [
    "pork meat"
  ],
  "porree": [
    "porree"
  ],
  "potato": [
    "potato"
  ],
  "potato-chips": [
    "potato chips"
  ],
  "potato-starch": [
    "potato starch"
  ],
  "pottukadalai-or-roasted-gram": [
    "pottukadalai or roasted gram",
    "pottukadalai",
    "roasted gram"
  ],
  "powder-sugar": [
    "powder sugar"
  ],
  "prawn": [
    "prawn"
  ],
  "psyllium-husk": [
    "psyllium husk"
  ],
  "puffed-lotus-seeds": [
    "puffed lotus seeds"
  ],
  "puffed-rice": [
    "puffed rice"
  ],
  "pumpkin-seeds": [
    "pumpkin seeds"
  ],
  "purple-sweet-potato": [
    "purple sweet potato"
  ],
  "raddish": [
    "raddish"
  ],
  "ragi-flour": [
    "ragi flour"
  ],
  "ragi-or-finger-millet": [
    "ragi or finger millet",
    "ragi",
    "finger millet"
  ],
  "raisins": [
    "raisins"
  ],
  "rapeseed-oil": [
    "rapeseed oil"
  ],
  "raspberry": [
    "raspberry"
  ],
  "raw-banana": [
    "raw banana"
  ],
  "raw-banana-flower": [
    "raw banana flower"
  ],
  "raw-mango": [
    "raw mango"
  ],
  "raw-or-green-jackfruit": [
    "raw or green jackfruit",
    "raw",
    "green jackfruit"
  ],
  "red-apple": [
    "red apple"
  ],
  "red-cabbage": [
    "red cabbage"
  ],
  "red-lentils": [
    "red lentils"
  ],
  "red-meat": [
    "red meat"
  ],
  "red-onion": [
    "red onion"
  ],
  "red-rice": [
    "red rice"
  ],
  "red-wine": [
    "red wine"
  ],
  "reisnudeln": [
    "reisnudeln"
  ],
  "rhabarber": [
    "rhabarber"
  ],
  "rice": [
    "rice"
  ],
  "rice-bran-oil": [
    "rice bran oil"
  ],
  "rice-flour": [
    "rice flour"
  ],
  "rice-paper": [
    "rice paper"
  ],
  "rice-vinegar": [
    "rice vinegar"
  ],
  "ricotta": [
    "ricotta"
  ],
  "ridge-gourd": [
    "ridge gourd"
  ],
  "risotto-paella-reis": [
    "risotto-paella reis"
  ],
  "roasted-sesame-seed-oil": [
    "roasted sesame seed oil"
  ],
  "rock-salt": [
    "rock salt"
  ],
  "rohu-fish": [
    "rohu fish"
  ],
  "roma-tomatoes": [
    "roma tomatoes"
  ],
  "rose-flavouring-essence": [
    "rose flavouring essence"
  ],
  "rose-petals": [
    "rose petals"
  ],
  "rose-water": [
    "rose water"
  ],
  "rosmarin": [
    "rosmarin"
  ],
  "rostzwiebeln": [
    "röstzwiebeln"
  ],
  "roti-or-chapati": [
    "roti or chapati",
    "roti",
    "chapati"
  ],
  "rucola": [
    "rucola"
  ],
  "rum": [
    "rum"
  ],
  "rye-flour": [
    "rye flour"
  ],
  "saffron": [
    "saffron"
  ],
  "sahne-zum-kochen": [
    "sahne zum kochen"
  ],
  "sajasauce": [
    "sajasauce"
  ],
  "sake": [
    "sake"
  ],
  "salami": [
    "salami"
  ],
  "salmon-fish-fillet": [
    "salmon fish fillet"
  ],
  "salt": [
    "salt"
  ],
  "sambal-oelek": [
    "sambal oelek"
  ],
  "sambar-powder": [
    "sambar powder"
  ],
  "samyang-buldak-hot-sauce": [
    "samyang buldak hot sauce"
  ],
  "sardines": [
    "sardines"
  ],
  "sausage": [
    "sausage"
  ],
  "scallops": [
    "scallops"
  ],
  "schlagsahne-32-fett": [
    "schlagsahne 32% fett"
  ],
  "seeraga-samba-rice": [
    "seeraga samba rice"
  ],
  "semolina": [
    "semolina"
  ],
  "sesame-oil": [
    "sesame oil"
  ],
  "sesame-seeds": [
    "sesame seeds"
  ],
  "shallots": [
    "shallots"
  ],
  "shaoxing-wine": [
    "shaoxing wine"
  ],
  "shiitake-pilze": [
    "shiitake pilze"
  ],
  "shopping-cart": [
    "shopping cart"
  ],
  "shrimp-paste": [
    "shrimp paste"
  ],
  "sichuan-peppercorn": [
    "sichuan peppercorn"
  ],
  "siracha-hot-chilli-sauce": [
    "siracha hot chilli sauce"
  ],
  "snackgurken": [
    "snackgurken"
  ],
  "soba-noodles": [
    "soba noodles"
  ],
  "sona-masoori-rice": [
    "sona masoori rice"
  ],
  "sourdough-loaf": [
    "sourdough loaf"
  ],
  "sourdough-starter": [
    "sourdough starter"
  ],
  "soy-milk": [
    "soy milk"
  ],
  "soya-beans": [
    "soya beans"
  ],
  "spaghetti": [
    "spaghetti"
  ],
  "spargel": [
    "spargel"
  ],
  "speicequark-40-fett": [
    "speicequark 40% fett"
  ],
  "speisequark-20-fett": [
    "speisequark 20% fett"
  ],
  "speisequark-magerstufe": [
    "speisequark magerstufe"
  ],
  "speisestarke": [
    "speisestärke"
  ],
  "spinach": [
    "spinach"
  ],
  "split-peas": [
    "split peas"
  ],
  "spring-onion": [
    "spring onion"
  ],
  "sprudelwasser": [
    "sprudelwasser"
  ],
  "squid": [
    "squid"
  ],
  "ssamjang": [
    "ssamjang"
  ],
  "stagenbohnen-breit": [
    "stagenbohnen breit"
  ],
  "star-anise": [
    "star anise"
  ],
  "staudensellerie": [
    "staudensellerie"
  ],
  "steak-meat-beef": [
    "steak meat, beef",
    "steak meat",
    "beef"
  ],
  "strawberry": [
    "strawberry"
  ],
  "sugar": [
    "sugar"
  ],
  "sugar-cubes": [
    "sugar cubes"
  ],
  "sunflower-oil": [
    "sunflower oil"
  ],
  "sunflower-seeds": [
    "sunflower seeds"
  ],
  "supplements": [
    "supplements"
  ],
  "sweet-chilli-sauce": [
    "sweet chilli sauce"
  ],
  "sweet-corn": [
    "sweet corn"
  ],
  "sweet-potato": [
    "sweet potato"
  ],
  "tagliatelle": [
    "tagliatelle"
  ],
  "tahini-sauce": [
    "tahini sauce"
  ],
  "tapioca-starch": [
    "tapioca starch"
  ],
  "taro-root": [
    "taro root"
  ],
  "tea-powder-taj-mahal": [
    "tea powder taj mahal"
  ],
  "tempeh": [
    "tempeh"
  ],
  "tender-coconut": [
    "tender coconut"
  ],
  "teri-yaki-woksauce": [
    "teri-yaki woksauce"
  ],
  "thyme": [
    "thyme"
  ],
  "tofu": [
    "tofu"
  ],
  "tomato": [
    "tomato"
  ],
  "tomato-ketchup": [
    "tomato ketchup"
  ],
  "tomato-paste": [
    "tomato paste"
  ],
  "toor-dal": [
    "toor dal"
  ],
  "tortillas": [
    "tortillas"
  ],
  "traubenkernol": [
    "traubenkernöl"
  ],
  "tricolor-quinoa": [
    "tricolor quinoa"
  ],
  "trinkschokolade": [
    "trinkschokolade"
  ],
  "tteok": [
    "tteok"
  ],
  "tuna-fillet": [
    "tuna fillet"
  ],
  "turmeric-powder": [
    "turmeric powder"
  ],
  "turnip": [
    "turnip"
  ],
  "urad-dal-whole": [
    "urad dal whole"
  ],
  "vanilla-bean": [
    "vanilla bean"
  ],
  "vegetable-stock-powder": [
    "vegetable stock powder"
  ],
  "vermicelli": [
    "vermicelli"
  ],
  "wakame-seaweed": [
    "wakame seaweed"
  ],
  "walnussol": [
    "walnussöl"
  ],
  "walnut": [
    "walnut"
  ],
  "wasabi-paste": [
    "wasabi paste"
  ],
  "water": [
    "water"
  ],
  "watermelon": [
    "watermelon"
  ],
  "weiss-pfeffer-gemahlen": [
    "weiß pfeffer gemahlen"
  ],
  "weizenmehl-405": [
    "weizenmehl 405"
  ],
  "weizenmehl-type-1050": [
    "weizenmehl type 1050"
  ],
  "weizenmehl-type-550": [
    "weizenmehl type 550"
  ],
  "whey-protein-powder": [
    "whey protein powder"
  ],
  "white-beans": [
    "white beans"
  ],
  "white-bread-slices": [
    "white bread slices"
  ],
  "white-chocolate": [
    "white chocolate"
  ],
  "white-quinoa": [
    "white quinoa"
  ],
  "white-wine": [
    "white wine"
  ],
  "worcestershire-sauce": [
    "worcestershire sauce"
  ],
  "xanthan-gum": [
    "xanthan gum"
  ],
  "zitrone-limette-elektrolyt-getrank": [
    "zitrone-limette elektrolyt-getränk"
  ],
  "zucchini": [
    "zucchini"
  ]
};
